version: '3.8'

services:
  app-review-monitor:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
