#!/usr/bin/env python3
"""
App Review Monitor - Web UI
Kullanıcıların ayarlarını yapabileceği basit web arayüzü
"""

from flask import Flask, render_template, request, redirect, url_for, flash, jsonify
import os
import requests
from datetime import datetime
import threading
import time
import logging
from typing import Dict, List, Optional

# Logging yapılandırması
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__)
app.secret_key = os.getenv('FLASK_SECRET_KEY', 'app_review_monitor_secret_key_2024')

# Global değişkenler
monitor_thread: Optional[threading.Thread] = None
monitor_running: bool = False
logs: List[Dict] = []

class WebConfig:
    """Web UI için konfigürasyon yönetimi"""
    
    @staticmethod
    def read_env() -> Dict[str, str]:
        """Mevcut .env dosyasını oku"""
        config = {}
        try:
            if os.path.exists('.env'):
                with open('.env', 'r', encoding='utf-8') as f:
                    for line in f:
                        line = line.strip()
                        if line and not line.startswith('#') and '=' in line:
                            key, value = line.split('=', 1)
                            config[key] = value
        except Exception as e:
            logger.error(f"Konfigürasyon okuma hatası: {e}")
        return config
    
    @staticmethod
    def write_env(config: Dict[str, str]) -> bool:
        """Konfigürasyonu .env dosyasına yaz"""
        try:
            with open('.env', 'w', encoding='utf-8') as f:
                f.write("# App Review Monitor Configuration\n")
                f.write("# Generated by Web UI\n\n")
                
                f.write("# Slack Configuration\n")
                f.write(f"SLACK_WEBHOOK_URL={config.get('SLACK_WEBHOOK_URL', '')}\n")
                f.write(f"SLACK_CHANNEL={config.get('SLACK_CHANNEL', '#app-reviews')}\n\n")
                
                f.write("# App Store Configuration\n")
                f.write(f"APP_STORE_APP_ID={config.get('APP_STORE_APP_ID', '')}\n")
                f.write(f"APP_STORE_COUNTRY={config.get('APP_STORE_COUNTRY', 'all')}\n\n")
                
                f.write("# Google Play Store Configuration\n")
                f.write(f"GOOGLE_PLAY_APP_ID={config.get('GOOGLE_PLAY_APP_ID', '')}\n")
                f.write(f"GOOGLE_PLAY_COUNTRY={config.get('GOOGLE_PLAY_COUNTRY', 'all')}\n\n")
                
                f.write("# Monitoring Configuration\n")
                f.write(f"CHECK_INTERVAL_MINUTES={config.get('CHECK_INTERVAL_MINUTES', '60')}\n")
                f.write(f"MAX_REVIEWS_PER_CHECK={config.get('MAX_REVIEWS_PER_CHECK', '10')}\n")
            return True
        except Exception as e:
            logger.error(f"Konfigürasyon yazma hatası: {e}")
            return False

def add_log(message: str, level: str = 'info') -> None:
    """Log mesajı ekle"""
    timestamp = datetime.now().strftime("%H:%M:%S")
    logs.append({
        'timestamp': timestamp,
        'message': message,
        'level': level
    })
    # Son 100 log'u tut
    if len(logs) > 100:
        logs.pop(0)
    
    # Console'a da yazdır
    logger.info(f"[{timestamp}] {message}")

def validate_config(config: Dict[str, str]) -> List[str]:
    """Konfigürasyon doğrulama"""
    errors = []
    
    # Slack webhook URL kontrolü
    if not config.get('SLACK_WEBHOOK_URL'):
        errors.append("Slack Webhook URL gerekli")
    elif not config['SLACK_WEBHOOK_URL'].startswith('https://hooks.slack.com/'):
        errors.append("Geçersiz Slack Webhook URL formatı")
    
    # App Store App ID kontrolü
    if not config.get('APP_STORE_APP_ID'):
        errors.append("App Store App ID gerekli")
    elif not config['APP_STORE_APP_ID'].isdigit():
        errors.append("App Store App ID sadece rakam olmalı")
    
    # Google Play App ID kontrolü
    if not config.get('GOOGLE_PLAY_APP_ID'):
        errors.append("Google Play App ID gerekli")
    
    # Check interval kontrolü
    try:
        interval = int(config.get('CHECK_INTERVAL_MINUTES', '60'))
        if interval < 1 or interval > 1440:  # 1 dakika - 24 saat
            errors.append("Kontrol aralığı 1-1440 dakika arasında olmalı")
    except ValueError:
        errors.append("Kontrol aralığı geçerli bir sayı olmalı")
    
    # Max reviews kontrolü
    try:
        max_reviews = int(config.get('MAX_REVIEWS_PER_CHECK', '10'))
        if max_reviews < 1 or max_reviews > 100:
            errors.append("Maksimum yorum sayısı 1-100 arasında olmalı")
    except ValueError:
        errors.append("Maksimum yorum sayısı geçerli bir sayı olmalı")
    
    return errors

@app.route('/')
def index():
    """Ana sayfa"""
    config = WebConfig.read_env()
    return render_template('index.html', config=config, logs=logs[-10:], monitor_running=monitor_running)

@app.route('/settings', methods=['GET', 'POST'])
def settings():
    """Ayarlar sayfası"""
    if request.method == 'POST':
        config = {
            'SLACK_WEBHOOK_URL': request.form.get('slack_webhook_url', ''),
            'SLACK_CHANNEL': request.form.get('slack_channel', '#app-reviews'),
            'GOOGLE_PLAY_APP_ID': request.form.get('google_play_app_id', ''),
            'GOOGLE_PLAY_COUNTRY': request.form.get('google_play_country', 'all'),
            'APP_STORE_APP_ID': request.form.get('app_store_app_id', ''),
            'APP_STORE_COUNTRY': request.form.get('app_store_country', 'all'),
            'CHECK_INTERVAL_MINUTES': request.form.get('check_interval', '60'),
            'MAX_REVIEWS_PER_CHECK': request.form.get('max_reviews', '10')
        }
        
        # Konfigürasyon doğrulama
        errors = validate_config(config)
        if errors:
            for error in errors:
                flash(error, 'error')
            return redirect(url_for('settings'))
        
        # Konfigürasyonu kaydet
        if WebConfig.write_env(config):
            add_log("Ayarlar kaydedildi", 'success')
            flash('Ayarlar başarıyla kaydedildi!', 'success')
        else:
            add_log("Ayarlar kaydedilemedi", 'error')
            flash('Ayarlar kaydedilemedi!', 'error')
        return redirect(url_for('index'))
    
    config = WebConfig.read_env()
    return render_template('settings.html', config=config)

@app.route('/test_slack', methods=['POST'])
def test_slack():
    """Slack webhook test et"""
    webhook_url = request.form.get('webhook_url')
    
    if not webhook_url:
        return jsonify({'success': False, 'message': 'Webhook URL gerekli'})
    
    if not webhook_url.startswith('https://hooks.slack.com/'):
        return jsonify({'success': False, 'message': 'Geçersiz Slack Webhook URL formatı'})
    
    test_message = {
        'text': '🧪 CmmntLnd - Test Mesajı',
        'username': 'CmmntLnd Monitor',
        'icon_emoji': ':star:',
        'attachments': [{
            'color': 'good',
            'fields': [{
                'title': '✅ Test Başarılı',
                'value': 'Slack entegrasyonu çalışıyor! WhatsApp, Facebook gibi uygulamalarınızın yorumları buraya gelecek.',
                'short': False
            }]
        }]
    }
    
    try:
        response = requests.post(webhook_url, json=test_message, timeout=10)
        if response.status_code == 200:
            add_log("Slack webhook test başarılı", 'success')
            return jsonify({'success': True, 'message': 'Test mesajı başarıyla gönderildi!'})
        else:
            add_log(f"Slack webhook test hatası: {response.status_code}", 'error')
            return jsonify({'success': False, 'message': f'Hata: {response.status_code}'})
    except requests.exceptions.Timeout:
        add_log("Slack test timeout hatası", 'error')
        return jsonify({'success': False, 'message': 'Bağlantı zaman aşımı'})
    except requests.exceptions.RequestException as e:
        add_log(f"Slack test bağlantı hatası: {e}", 'error')
        return jsonify({'success': False, 'message': f'Bağlantı hatası: {str(e)}'})
    except Exception as e:
        add_log(f"Slack test genel hatası: {e}", 'error')
        return jsonify({'success': False, 'message': f'Beklenmeyen hata: {str(e)}'})

@app.route('/start_monitor', methods=['POST'])
def start_monitor():
    """Monitor'u başlat"""
    global monitor_thread, monitor_running
    
    if monitor_running:
        return jsonify({'success': False, 'message': 'Monitor zaten çalışıyor'})
    
    try:
        # Monitor thread'ini başlat
        monitor_thread = threading.Thread(target=run_monitor)
        monitor_thread.daemon = True
        monitor_thread.start()
        monitor_running = True
        add_log("Monitor başlatıldı", 'success')
        return jsonify({'success': True, 'message': 'Monitor başlatıldı!'})
    except Exception as e:
        add_log(f"Monitor başlatma hatası: {str(e)}", 'error')
        return jsonify({'success': False, 'message': f'Hata: {str(e)}'})

@app.route('/stop_monitor', methods=['POST'])
def stop_monitor():
    """Monitor'u durdur"""
    global monitor_running
    
    monitor_running = False
    add_log("Monitor durduruldu", 'info')
    return jsonify({'success': True, 'message': 'Monitor durduruldu!'})

@app.route('/logs')
def get_logs():
    """Log'ları JSON olarak döndür"""
    return jsonify(logs[-20:])

def run_monitor():
    """Monitor'u çalıştır (thread içinde)"""
    global monitor_running
    
    try:
        from app_review_monitor import AppReviewMonitor
        from config import Config
        
        # .env dosyasını yeniden yükle
        add_log("Monitor thread başlatılıyor, ayarlar yükleniyor...", 'info')
        from dotenv import load_dotenv
        load_dotenv()  # .env dosyasını tekrar yükle
        
        monitor = AppReviewMonitor()
        add_log(f"Monitor hazır - Slack Webhook: {monitor.config.SLACK_WEBHOOK_URL[:50]}...", 'info')
        
        while monitor_running:
            try:
                add_log("Yorum kontrol süreci başlatılıyor...", 'info')
                monitor.check_and_send_reviews()
                add_log("Yorum kontrolü tamamlandı", 'success')
                
                # Bekleme süresi - daha kısa aralıklarla kontrol et
                for _ in range(monitor.config.CHECK_INTERVAL_MINUTES * 60):
                    if not monitor_running:
                        break
                    time.sleep(1)
                    
            except Exception as e:
                add_log(f"Monitor hatası: {str(e)}", 'error')
                time.sleep(60)  # Hata durumunda 1 dakika bekle
                
    except Exception as e:
        add_log(f"Monitor başlatma hatası: {str(e)}", 'error')
        monitor_running = False
    finally:
        # Sadece thread sonlandığında monitor_running'i false yap
        if monitor_running:
            add_log("Monitor thread sonlandırıldı", 'info')
        monitor_running = False

if __name__ == '__main__':
    add_log("Web UI başlatıldı", 'info')
    app.run(debug=True, host='0.0.0.0', port=5000)
