#!/usr/bin/env python3
"""
App Review Monitor - Web UI
Kullanıcıların ayarlarını yapabileceği basit web arayüzü
"""

from flask import Flask, render_template, request, redirect, url_for, flash, jsonify
import os
import sys
import requests
from datetime import datetime
import threading
import time
import logging
from typing import Dict, List, Optional
import fcntl

# Logging yapılandırması
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__)
app.secret_key = os.getenv('FLASK_SECRET_KEY', 'app_review_monitor_secret_key_2024')

# Global değişkenler
monitor_thread: Optional[threading.Thread] = None
monitor_running: bool = False
monitor_start_lock = threading.Lock()
monitor_lock_fd = None
logs: List[Dict] = []
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ENV_PATH = os.path.join(BASE_DIR, '.env')
# web_ui içindeki monitor thread ile main.py aynı dosyayı paylaşır — aynı anda tek yorum döngüsü
MONITOR_LOCK_PATH = os.path.join(BASE_DIR, '.monitor.lock')
# Aynı proje klasöründe ikinci bir Flask/Web UI süreci açılmasın (farklı port bile olsa)
WEB_UI_SINGLETON_LOCK_PATH = os.path.join(BASE_DIR, '.web_ui.lock')
_web_ui_singleton_fd: Optional[object] = None

class WebConfig:
    """Web UI için konfigürasyon yönetimi"""
    
    @staticmethod
    def read_env() -> Dict[str, str]:
        """Mevcut .env dosyasını oku"""
        config = {}
        try:
            if os.path.exists(ENV_PATH):
                with open(ENV_PATH, 'r', encoding='utf-8') as f:
                    for line in f:
                        line = line.strip()
                        if line and not line.startswith('#') and '=' in line:
                            key, value = line.split('=', 1)
                            config[key] = value
        except Exception as e:
            logger.error(f"Konfigürasyon okuma hatası: {e}")
        return config
    
    @staticmethod
    def write_env(config: Dict[str, str]) -> bool:
        """Konfigürasyonu .env dosyasına yaz"""
        try:
            with open(ENV_PATH, 'w', encoding='utf-8') as f:
                f.write("# App Review Monitor Configuration\n")
                f.write("# Generated by Web UI\n\n")
                
                f.write("# Slack Configuration\n")
                f.write(f"SLACK_WEBHOOK_URL={config.get('SLACK_WEBHOOK_URL', '')}\n")
                f.write(f"SLACK_CHANNEL={config.get('SLACK_CHANNEL', '#app-reviews')}\n\n")
                
                f.write("# App Store Configuration\n")
                f.write(f"APP_STORE_APP_ID={config.get('APP_STORE_APP_ID', '')}\n")
                f.write(f"APP_STORE_COUNTRY={config.get('APP_STORE_COUNTRY', 'all')}\n\n")
                
                f.write("# Google Play Store Configuration\n")
                f.write(f"GOOGLE_PLAY_APP_ID={config.get('GOOGLE_PLAY_APP_ID', '')}\n")
                f.write(f"GOOGLE_PLAY_COUNTRY={config.get('GOOGLE_PLAY_COUNTRY', 'all')}\n\n")
                
                f.write("# Monitoring Configuration\n")
                f.write(f"CHECK_INTERVAL_MINUTES={config.get('CHECK_INTERVAL_MINUTES', '60')}\n")
                f.write(f"MAX_REVIEWS_PER_CHECK={config.get('MAX_REVIEWS_PER_CHECK', '10')}\n")
            return True
        except Exception as e:
            logger.error(f"Konfigürasyon yazma hatası: {e}")
            return False

def add_log(message: str, level: str = 'info') -> None:
    """Log mesajı ekle"""
    timestamp = datetime.now().strftime("%H:%M:%S")
    logs.append({
        'timestamp': timestamp,
        'message': message,
        'level': level
    })
    # Son 100 log'u tut
    if len(logs) > 100:
        logs.pop(0)
    
    # Console'a da yazdır
    logger.info(f"[{timestamp}] {message}")

def validate_config(config: Dict[str, str]) -> List[str]:
    """Konfigürasyon doğrulama"""
    errors = []
    
    # Slack webhook URL kontrolü
    if not config.get('SLACK_WEBHOOK_URL'):
        errors.append("Slack Webhook URL gerekli")
    elif not config['SLACK_WEBHOOK_URL'].startswith('https://hooks.slack.com/'):
        errors.append("Geçersiz Slack Webhook URL formatı")
    
    # App Store App ID kontrolü
    if not config.get('APP_STORE_APP_ID'):
        errors.append("App Store App ID gerekli")
    elif not config['APP_STORE_APP_ID'].isdigit():
        errors.append("App Store App ID sadece rakam olmalı")
    
    # Google Play App ID kontrolü
    if not config.get('GOOGLE_PLAY_APP_ID'):
        errors.append("Google Play App ID gerekli")
    
    # Check interval kontrolü
    try:
        interval = int(config.get('CHECK_INTERVAL_MINUTES', '60'))
        if interval < 1 or interval > 1440:  # 1 dakika - 24 saat
            errors.append("Kontrol aralığı 1-1440 dakika arasında olmalı")
    except ValueError:
        errors.append("Kontrol aralığı geçerli bir sayı olmalı")
    
    # Max reviews kontrolü
    try:
        max_reviews = int(config.get('MAX_REVIEWS_PER_CHECK', '10'))
        if max_reviews < 1 or max_reviews > 100:
            errors.append("Maksimum yorum sayısı 1-100 arasında olmalı")
    except ValueError:
        errors.append("Maksimum yorum sayısı geçerli bir sayı olmalı")
    
    return errors

@app.route('/')
def index():
    """Ana sayfa"""
    config = WebConfig.read_env()
    thread_alive = bool(monitor_thread and monitor_thread.is_alive())
    return render_template(
        'index.html',
        config=config,
        logs=logs[-10:],
        monitor_running=monitor_running,
        process_pid=os.getpid(),
        monitor_thread_alive=thread_alive,
    )


@app.route('/api/status')
def api_status():
    """Kaç süreç / monitor thread — teşhis için"""
    thread_alive = bool(monitor_thread and monitor_thread.is_alive())
    return jsonify({
        'process_pid': os.getpid(),
        'monitor_running_flag': monitor_running,
        'monitor_thread_alive': thread_alive,
        'monitor_worker_threads': 1 if thread_alive else 0,
        'note': 'Flask ana süreç 1; Başlat ile en fazla 1 adet daemon monitor thread eklenir.',
    })

@app.route('/settings', methods=['GET', 'POST'])
def settings():
    """Ayarlar sayfası"""
    if request.method == 'POST':
        config = {
            'SLACK_WEBHOOK_URL': request.form.get('slack_webhook_url', ''),
            'SLACK_CHANNEL': request.form.get('slack_channel', '#app-reviews'),
            'GOOGLE_PLAY_APP_ID': request.form.get('google_play_app_id', ''),
            'GOOGLE_PLAY_COUNTRY': request.form.get('google_play_country', 'all'),
            'APP_STORE_APP_ID': request.form.get('app_store_app_id', ''),
            'APP_STORE_COUNTRY': request.form.get('app_store_country', 'all'),
            'CHECK_INTERVAL_MINUTES': request.form.get('check_interval', '60'),
            'MAX_REVIEWS_PER_CHECK': request.form.get('max_reviews', '10')
        }
        
        # Konfigürasyon doğrulama
        errors = validate_config(config)
        if errors:
            for error in errors:
                flash(error, 'error')
            return redirect(url_for('settings'))
        
        # Konfigürasyonu kaydet
        if WebConfig.write_env(config):
            add_log("Ayarlar kaydedildi", 'success')
            flash('Ayarlar başarıyla kaydedildi!', 'success')
        else:
            add_log("Ayarlar kaydedilemedi", 'error')
            flash('Ayarlar kaydedilemedi!', 'error')
        return redirect(url_for('index'))
    
    config = WebConfig.read_env()
    return render_template('settings.html', config=config)

@app.route('/test_slack', methods=['POST'])
def test_slack():
    """Slack webhook test et"""
    webhook_url = request.form.get('webhook_url')
    
    if not webhook_url:
        return jsonify({'success': False, 'message': 'Webhook URL gerekli'})
    
    if not webhook_url.startswith('https://hooks.slack.com/'):
        return jsonify({'success': False, 'message': 'Geçersiz Slack Webhook URL formatı'})
    
    test_message = {
        'text': '🧪 CmmntLnd - Test Mesajı',
        'username': 'CmmntLnd Monitor',
        'icon_emoji': ':star:',
        'attachments': [{
            'color': 'good',
            'fields': [{
                'title': '✅ Test Başarılı',
                'value': 'Slack entegrasyonu çalışıyor! WhatsApp, Facebook gibi uygulamalarınızın yorumları buraya gelecek.',
                'short': False
            }]
        }]
    }
    
    try:
        response = requests.post(webhook_url, json=test_message, timeout=10)
        if response.status_code == 200:
            add_log("Slack webhook test başarılı", 'success')
            return jsonify({'success': True, 'message': 'Test mesajı başarıyla gönderildi!'})
        else:
            add_log(f"Slack webhook test hatası: {response.status_code}", 'error')
            return jsonify({'success': False, 'message': f'Hata: {response.status_code}'})
    except requests.exceptions.Timeout:
        add_log("Slack test timeout hatası", 'error')
        return jsonify({'success': False, 'message': 'Bağlantı zaman aşımı'})
    except requests.exceptions.RequestException as e:
        add_log(f"Slack test bağlantı hatası: {e}", 'error')
        return jsonify({'success': False, 'message': f'Bağlantı hatası: {str(e)}'})
    except Exception as e:
        add_log(f"Slack test genel hatası: {e}", 'error')
        return jsonify({'success': False, 'message': f'Beklenmeyen hata: {str(e)}'})

@app.route('/start_monitor', methods=['POST'])
def start_monitor():
    """Monitor'u başlat"""
    global monitor_thread, monitor_running

    with monitor_start_lock:
        if monitor_running and monitor_thread and monitor_thread.is_alive():
            return jsonify({'success': False, 'message': 'Monitor zaten çalışıyor'})

        try:
            # Race condition engeli: önce running flag'i aç, sonra thread başlat
            monitor_running = True
            monitor_thread = threading.Thread(target=run_monitor)
            monitor_thread.daemon = True
            monitor_thread.start()
            add_log("Monitor başlatıldı", 'success')
            return jsonify({'success': True, 'message': 'Monitor başlatıldı!'})
        except Exception as e:
            monitor_running = False
            add_log(f"Monitor başlatma hatası: {str(e)}", 'error')
            return jsonify({'success': False, 'message': f'Hata: {str(e)}'})

@app.route('/stop_monitor', methods=['POST'])
def stop_monitor():
    """Monitor'u durdur"""
    global monitor_running
    
    monitor_running = False
    add_log("Monitor durduruldu", 'info')
    return jsonify({'success': True, 'message': 'Monitor durduruldu!'})

@app.route('/database')
def database():
    """Database/Export sayfası"""
    config = WebConfig.read_env()
    return render_template('database.html', config=config)

def _export_review_row(review: Dict) -> List:
    """CSV satırı için alanları normalize et."""
    date_val = review.get('date', '')
    if isinstance(date_val, datetime):
        date_val = date_val.strftime('%Y-%m-%d %H:%M:%S')
    platform = review.get('platform') or (
        'iOS' if review.get('source') == 'App Store' else 'Android'
    )
    return [
        platform,
        review.get('source', ''),
        review.get('review_id', ''),
        review.get('rating', ''),
        review.get('title', ''),
        review.get('content', ''),
        review.get('author', ''),
        date_val,
        review.get('version', ''),
        review.get('url', ''),
        review.get('country', ''),
    ]


@app.route('/export_reviews', methods=['POST'])
def export_reviews():
    """Geçmiş yorumları export et"""
    try:
        time_period = request.form.get('time_period')
        export_format = request.form.get('export_format', 'csv')
        platforms = request.form.getlist('platforms')
        if not platforms:
            platforms = ['app_store', 'google_play']

        from datetime import timedelta
        from dotenv import load_dotenv
        from config import Config
        from app_review_monitor import AppReviewMonitor
        import csv
        import io
        import json
        from flask import make_response

        load_dotenv(dotenv_path=ENV_PATH, override=True)
        Config.reload_from_env()

        if time_period == '15_days':
            days = 15
        elif time_period == '1_month':
            days = 30
        elif time_period == '2_months':
            days = 60
        elif time_period == '3_months':
            days = 90
        elif time_period == '6_months':
            days = 180
        elif time_period == '1_year':
            days = 365
        else:
            return jsonify({'success': False, 'message': 'Geçersiz zaman aralığı'}), 400

        start_date = datetime.now() - timedelta(days=days)
        add_log(f"Export başladı: {time_period}, platformlar={platforms}", 'info')

        monitor = AppReviewMonitor()

        # Önce DB'den oku (anında); aralıkta kayıt yoksa API'den çekip DB'ye yaz
        historical_reviews = monitor.db.get_reviews_since(start_date, platforms=platforms)
        if not historical_reviews:
            add_log("DB'de kayıt yok — API'den çekiliyor ve DB'ye yazılıyor...", 'info')
            fetched = monitor.get_historical_reviews(start_date, platforms=platforms)
            for review in fetched:
                # Geçmiş arşiv; Slack'e basılmasın diye gönderilmiş işaretle
                monitor.db.upsert_review(review, sent=True)
            historical_reviews = monitor.db.get_reviews_since(start_date, platforms=platforms)

        ios_count = sum(1 for r in historical_reviews if r.get('source') == 'App Store')
        android_count = sum(1 for r in historical_reviews if r.get('source') == 'Google Play')
        add_log(
            f"Export veri: toplam={len(historical_reviews)}, iOS={ios_count}, Android={android_count}",
            'info',
        )

        stamp = datetime.now().strftime('%Y%m%d')

        if export_format == 'csv':
            output = io.StringIO()
            writer = csv.writer(output)
            writer.writerow([
                'Platform', 'Store', 'Review ID', 'Rating', 'Title', 'Content',
                'Author', 'Date', 'Version', 'URL', 'Country',
            ])
            for review in historical_reviews:
                writer.writerow(_export_review_row(review))

            response = make_response('\ufeff' + output.getvalue())
            response.headers['Content-Type'] = 'text/csv; charset=utf-8'
            response.headers['Content-Disposition'] = (
                f'attachment; filename=app_reviews_{time_period}_{stamp}.csv'
            )
            add_log(f"CSV export tamamlandı: {len(historical_reviews)} yorum", 'success')
            return response

        if export_format == 'json':
            payload = []
            for review in historical_reviews:
                row = dict(zip(
                    ['platform', 'store', 'review_id', 'rating', 'title', 'content',
                     'author', 'date', 'version', 'url', 'country'],
                    _export_review_row(review),
                ))
                payload.append(row)
            response = make_response(json.dumps(payload, ensure_ascii=False, indent=2))
            response.headers['Content-Type'] = 'application/json; charset=utf-8'
            response.headers['Content-Disposition'] = (
                f'attachment; filename=app_reviews_{time_period}_{stamp}.json'
            )
            add_log(f"JSON export tamamlandı: {len(historical_reviews)} yorum", 'success')
            return response

        return jsonify({'success': False, 'message': 'Desteklenmeyen format'}), 400

    except Exception as e:
        add_log(f"Export hatası: {str(e)}", 'error')
        return jsonify({'success': False, 'message': f'Hata: {str(e)}'}), 500

@app.route('/backfill', methods=['POST'])
def backfill():
    """Tüm geçmiş yorumları çekip DB'ye doldur (Slack'e göndermeden)."""
    try:
        platforms = request.form.getlist('platforms')
        if not platforms:
            platforms = ['app_store', 'google_play']

        from dotenv import load_dotenv
        from config import Config
        from app_review_monitor import AppReviewMonitor

        load_dotenv(dotenv_path=ENV_PATH, override=True)
        Config.reload_from_env()

        add_log(f"Backfill başladı (platformlar={platforms})...", 'info')
        monitor = AppReviewMonitor()
        result = monitor.backfill_database(platforms=platforms)
        add_log(
            f"Backfill tamamlandı: {result['total']} kayıt "
            f"(iOS {result['ios']}, Android {result['android']})",
            'success',
        )
        return jsonify({'success': True, 'message': 'Backfill tamamlandı', 'result': result})
    except Exception as e:
        add_log(f"Backfill hatası: {str(e)}", 'error')
        return jsonify({'success': False, 'message': f'Hata: {str(e)}'}), 500


@app.route('/send_summary', methods=['POST'])
def send_summary():
    """Günlük istatistik özetini hemen çek ve Slack'e gönder."""
    try:
        from dotenv import load_dotenv
        from config import Config
        from app_review_monitor import AppReviewMonitor

        load_dotenv(dotenv_path=ENV_PATH, override=True)
        Config.reload_from_env()

        add_log("Günlük özet manuel olarak tetiklendi...", 'info')
        monitor = AppReviewMonitor()
        ok = monitor.send_daily_summary()
        if ok:
            add_log("Günlük özet Slack'e gönderildi", 'success')
            return jsonify({'success': True, 'message': 'Özet gönderildi!'})
        add_log("Günlük özet gönderilemedi", 'error')
        return jsonify({'success': False, 'message': 'Slack gönderimi başarısız'}), 500
    except Exception as e:
        add_log(f"Özet hatası: {str(e)}", 'error')
        return jsonify({'success': False, 'message': f'Hata: {str(e)}'}), 500


@app.route('/api/stats')
def api_stats():
    """En son istatistikleri JSON olarak döndür (UI gösterimi için)."""
    try:
        from app_review_monitor import AppReviewMonitor
        monitor = AppReviewMonitor()
        return jsonify({
            'success': True,
            'ios': monitor.db.get_latest_stats('iOS'),
            'android': monitor.db.get_latest_stats('Android'),
            'review_counts': {
                'ios': monitor.db.count_reviews('iOS'),
                'android': monitor.db.count_reviews('Android'),
            },
        })
    except Exception as e:
        return jsonify({'success': False, 'message': str(e)}), 500


@app.route('/api/reviews')
def api_reviews():
    """DB'deki yorumları filtreli + sayfalı döndür (UI tablosu için)."""
    try:
        from app_review_monitor import AppReviewMonitor

        platform = request.args.get('platform') or None
        rating = request.args.get('rating', type=int)
        search = request.args.get('search') or None
        sent_arg = request.args.get('sent')
        sent = None
        if sent_arg == '1':
            sent = True
        elif sent_arg == '0':
            sent = False

        page = max(1, request.args.get('page', default=1, type=int))
        per_page = min(100, max(5, request.args.get('per_page', default=25, type=int)))
        offset = (page - 1) * per_page

        monitor = AppReviewMonitor()
        result = monitor.db.query_reviews(
            platform=platform,
            rating=rating,
            search=search,
            sent=sent,
            limit=per_page,
            offset=offset,
        )
        result['page'] = page
        result['per_page'] = per_page
        result['pages'] = max(1, (result['total'] + per_page - 1) // per_page)
        result['success'] = True
        return jsonify(result)
    except Exception as e:
        return jsonify({'success': False, 'message': str(e)}), 500


@app.route('/logs')
def get_logs():
    """Log'ları JSON olarak döndür"""
    return jsonify(logs[-20:])

def _maybe_send_daily_summary(monitor, target_time: str) -> None:
    """Hedef saat geçmiş ve bugün özet gönderilmemişse günlük özeti gönder.

    'Bugün gönderildi mi' kontrolü DB'deki app_stats kaydından yapılır (idempotent).
    """
    now = datetime.now()
    today = now.strftime('%Y-%m-%d')

    try:
        hour, minute = (int(x) for x in target_time.split(':'))
    except (ValueError, AttributeError):
        hour, minute = 10, 0

    # Hedef saate ulaşılmadıysa bekle
    if (now.hour, now.minute) < (hour, minute):
        return

    # Bugün zaten bir snapshot alındıysa (özet gönderildiyse) tekrar gönderme
    latest = monitor.db.get_latest_stats('iOS')
    if latest and latest.get('captured_date') == today:
        return

    add_log(f"Günlük özet gönderiliyor ({target_time})...", 'info')
    if monitor.send_daily_summary():
        add_log("Günlük özet Slack'e gönderildi", 'success')
    else:
        add_log("Günlük özet gönderilemedi", 'error')


def run_monitor():
    """Monitor'u çalıştır (thread içinde)"""
    global monitor_running, monitor_lock_fd

    try:
        # Aynı anda ikinci monitor sürecini engelle (process-level lock)
        monitor_lock_fd = open(MONITOR_LOCK_PATH, 'w')
        fcntl.flock(monitor_lock_fd.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)

        # .env dosyasını yeniden yükle
        add_log("Monitor thread başlatılıyor, ayarlar yükleniyor...", 'info')
        from dotenv import load_dotenv
        load_dotenv(dotenv_path=ENV_PATH, override=True)  # .env dosyasını tekrar yükle

        from app_review_monitor import AppReviewMonitor
        
        # SADECE BİR KEZ AppReviewMonitor oluştur
        monitor = AppReviewMonitor()
        add_log(f"Monitor hazır - Slack Webhook: {monitor.config.SLACK_WEBHOOK_URL[:50]}...", 'info')
        add_log(f"Monitor sent_reviews boyutu: {len(monitor.sent_reviews)}", 'info')

        daily_summary_time = os.getenv('DAILY_SUMMARY_TIME', '10:00')
        
        while monitor_running:
            try:
                add_log("Yorum kontrol süreci başlatılıyor...", 'info')
                
                # Disk ile birleştir (= kullanma: disk yazılamazsa boş set belleği sıfırlar, aynı yorumlar saatte bir tekrar gider)
                disk_ids = monitor.load_sent_reviews()
                monitor.sent_reviews |= disk_ids
                add_log(f"Sent reviews birleştirildi (bellek ∪ disk): {len(monitor.sent_reviews)} adet", 'info')
                
                monitor.check_and_send_reviews()
                add_log("Yorum kontrolü tamamlandı", 'success')

                # Günlük özet: hedef saat geçtiyse ve bugün henüz gönderilmediyse gönder
                try:
                    _maybe_send_daily_summary(monitor, daily_summary_time)
                except Exception as e:
                    add_log(f"Günlük özet kontrolü hatası: {e}", 'error')
                
                # Bekleme süresi - daha kısa aralıklarla kontrol et
                for _ in range(monitor.config.CHECK_INTERVAL_MINUTES * 60):
                    if not monitor_running:
                        break
                    time.sleep(1)
                    
            except Exception as e:
                add_log(f"Monitor hatası: {str(e)}", 'error')
                time.sleep(60)  # Hata durumunda 1 dakika bekle
                
    except BlockingIOError:
        add_log("Monitor zaten başka bir süreçte çalışıyor, ikinci kez başlatılmadı", 'warning')
        monitor_running = False
    except PermissionError as e:
        add_log(f"Monitor başlatma hatası: .env erişim izni yok ({ENV_PATH}) - {str(e)}", 'error')
        monitor_running = False
    except Exception as e:
        add_log(f"Monitor başlatma hatası: {str(e)}", 'error')
        monitor_running = False
    finally:
        if monitor_lock_fd:
            try:
                fcntl.flock(monitor_lock_fd.fileno(), fcntl.LOCK_UN)
                monitor_lock_fd.close()
            except Exception:
                pass
            monitor_lock_fd = None

        # Sadece thread sonlandığında monitor_running'i false yap
        if monitor_running:
            add_log("Monitor thread sonlandırıldı", 'info')
        monitor_running = False

def _acquire_web_ui_singleton_lock() -> None:
    """Bu proje dizininde tek Web UI süreci (ALLOW_MULTIPLE_WEB_UI=1 ile kapatılabilir)."""
    global _web_ui_singleton_fd
    if os.environ.get('ALLOW_MULTIPLE_WEB_UI', '').strip() == '1':
        return
    fd = open(WEB_UI_SINGLETON_LOCK_PATH, 'w')
    try:
        fcntl.flock(fd.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        fd.close()
        try:
            with open(WEB_UI_SINGLETON_LOCK_PATH, 'r', encoding='utf-8') as rf:
                other = rf.read().strip() or '?'
        except OSError:
            other = '?'
        print(
            f"❌ Bu proje için Web UI zaten çalışıyor (.web_ui.lock, diğer PID/port: {other}).\n"
            f"   İkinci süreç Slack'te çift bildirim üretebilir. Önce eski süreci durdur.\n"
            f"   Geliştirici modunda çok süreç istiyorsan: ALLOW_MULTIPLE_WEB_UI=1 python web_ui.py ...",
            file=sys.stderr,
        )
        raise SystemExit(1) from None
    fd.write(f"pid={os.getpid()}\n")
    fd.flush()
    _web_ui_singleton_fd = fd


if __name__ == '__main__':
    _acquire_web_ui_singleton_lock()

    # Port parametresi kontrol et
    port = 5000
    if len(sys.argv) > 1 and sys.argv[1] == '--port':
        try:
            port = int(sys.argv[2])
        except (IndexError, ValueError):
            port = 5000

    if _web_ui_singleton_fd is not None:
        _web_ui_singleton_fd.write(f"port={port}\n")
        _web_ui_singleton_fd.flush()

    add_log(f"Web UI başlatıldı - Port: {port} (PID {os.getpid()})", 'info')
    app.run(debug=False, use_reloader=False, host='0.0.0.0', port=port)
